name: Build and deploy ASP.Net Core app to Azure Web App - CorpsAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write   # required for OIDC login
      contents: read    # required for checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Publish .NET app
        run: dotnet publish -c Release -o ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D3D27A86D0AB422BAE131D0720B4191F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DE19712C77064F0A8171630F413471AE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_32D1AD39A8C64BB6AAB28FBD1DCA176F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CorpsAPI'
          slot-name: 'Production'
          package: ./publish
